name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    uses: lexmag/elixir-actions/.github/workflows/lint.yml@v1

  test:
    name: Test suite
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        versions:
          - otp: 20.3
            elixir: 1.7
          - otp: 24
            elixir: 1.13

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir environment
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          otp-version: ${{ matrix.versions.otp }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test
